# Generated by Django 3.1 on 2021-10-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
                ('school', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('weapon', models.CharField(max_length=2)),
                ('damage', models.CharField(max_length=64)),
                ('armor', models.CharField(max_length=64)),
            ],
        ),
    ]
