# Generated by Django 3.1 on 2021-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('Attacker', 'Attacker'), ('Supporter', 'Supporter'), ('Tank', 'Tank'), ('Healer', 'Healer'), ('Tactical', 'Tactical')], max_length=64),
        ),
    ]
