# Generated by Django 3.1 on 2021-11-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20211101_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star')]),
        ),
    ]
