# Generated by Django 3.1 on 2021-11-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20211101_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.FilePathField(default='Shiroko.png', max_length=64, path='/characters/img/'),
            preserve_default=False,
        ),
    ]
