# Generated by Django 3.1 on 2021-11-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.FilePathField(max_length=64, path='/static/characters/img/'),
        ),
    ]
