# Generated by Django 3.1 on 2021-11-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20211101_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
    ]
