# Generated by Django 3.1 on 2021-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_remove_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.CharField(choices=[('*', '1 Star'), ('**', '2 Star'), ('***', '3 Star')], max_length=3),
        ),
    ]
