# Generated by Django 3.1 on 2021-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20211102_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='excost',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.CharField(choices=[('Light', 'Light'), ('Heavy', 'Heavy'), ('Special', 'Special')], max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='damage',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Explosive', 'Explosive'), ('Piercing', 'Piercing'), ('Mystic', 'Mystic')], max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('Attacker', 'Attacker'), ('Support', 'Support'), ('Tank', 'Tank'), ('Healer', 'Healer'), ('Tactical', 'Tactical')], max_length=64),
        ),
    ]
