# Generated by Django 3.1 on 2021-12-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20211202_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.CharField(choices=[('Light', 'Light'), ('Heavy', 'Heavy'), ('Special', 'Special')], default='Light', max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='damage',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Explosive', 'Explosive'), ('Piercing', 'Piercing'), ('Mystic', 'Mystic')], default='Normal', max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='excost',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='position',
            field=models.CharField(choices=[('Front', 'Front'), ('Middle', 'Middle'), ('Back', 'Back')], default='Front', max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.CharField(choices=[('*', '1 Star'), ('**', '2 Star'), ('***', '3 Star')], default='*', max_length=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('Attacker', 'Attacker'), ('Support', 'Support'), ('Tank', 'Tank'), ('Healer', 'Healer'), ('Tactical', 'Tactical')], default='Attacker', max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='school',
            field=models.CharField(choices=[('Abydos', 'Abydos'), ('Gehenna', 'Gehenna'), ('Millennium', 'Millennium'), ('Trinity', 'Trinity'), ('Hyakkiyako', 'Hyakkiyako'), ('Shanhaijing', 'Shanhaijing'), ('Red Winter', 'Red Winter'), ('Valkyrie', 'Valkyrie'), ('Arius', 'Arius')], default='Abydos', max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.CharField(choices=[('HG', 'HG'), ('AR', 'AR'), ('MG', 'MG'), ('SG', 'SG'), ('SMG', 'SMG'), ('SR', 'SR'), ('RF', 'RF'), ('GL', 'GL')], default='HG', max_length=3),
        ),
    ]
