# Generated by Django 3.1 on 2021-12-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_auto_20211202_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='ex_desc',
            new_name='ex_Desc',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='ex_title',
            new_name='ex_Title',
        ),
    ]
