# Generated by Django 3.1 on 2021-12-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_auto_20211202_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='armor',
            new_name='Armor',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='damage',
            new_name='Damage',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='excost',
            new_name='Ex_Cost',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='ex_Desc',
            new_name='Ex_Desc',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='ex_Title',
            new_name='Ex_Title',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='position',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='rarity',
            new_name='Rarity',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='role',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='school',
            new_name='School',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='weapon',
            new_name='Weapon',
        ),
    ]
