# Generated by Django 3.1 on 2021-12-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20211202_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Ex_Desc',
            field=models.TextField(default='', max_length=192),
        ),
    ]
