# Generated by Django 3.1 on 2021-12-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_auto_20211202_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Ex_Desc',
            field=models.TextField(default='', max_length=384),
        ),
    ]
