# Generated by Django 3.1 on 2021-12-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20211202_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='Ex_Cost',
            new_name='EX_Cost',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Ex_Desc',
            new_name='EX_Desc',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Ex_Title',
            new_name='EX_Title',
        ),
    ]
