# Generated by Django 3.1 on 2021-12-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20211202_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Normal_Desc',
            field=models.TextField(default='', max_length=384),
        ),
        migrations.AlterField(
            model_name='character',
            name='Passive_Desc',
            field=models.TextField(default='', max_length=384),
        ),
        migrations.AlterField(
            model_name='character',
            name='Sub_Desc',
            field=models.TextField(default='', max_length=384),
        ),
    ]
