# Generated by Django 3.1 on 2021-12-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_auto_20211202_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='Normal_Desc',
            new_name='Basic_Desc',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Normal_Title',
            new_name='Basic_Title',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Passive_Desc',
            new_name='Enhanced_Desc',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Passive_Title',
            new_name='Enhanced_Title',
        ),
    ]
