# Generated by Django 3.1 on 2021-12-03 13:51

import characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_auto_20211202_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Portrait_FilePath',
            field=models.FilePathField(default='', path=characters.models.imagess_path),
        ),
    ]
