# Generated by Django 3.1 on 2021-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_auto_20211203_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Portrait_FilePath',
            field=models.FilePathField(allow_folders=True, default='', path='C:\\Users\\Eric Li\\Documents\\BlueArchiveDB\\bluearchivedb\\characters\\static\\characters\\img\\'),
        ),
    ]
