# Generated by Django 3.1 on 2021-12-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_auto_20211203_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='Portrait_FilePath',
        ),
    ]
