# Generated by Django 3.1 on 2021-12-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_auto_20211203_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='Enhanced_Desc',
            new_name='enhanced_desc',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='Enhanced_Title',
            new_name='enhanced_title',
        ),
    ]
