# Generated by Django 3.1 on 2021-12-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0029_auto_20211203_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='portrait_img_path',
            field=models.CharField(default='characters/img/', max_length=64),
        ),
    ]
