# Generated by Django 3.1 on 2021-12-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0030_character_portrait_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='portrait_img_path',
        ),
    ]
