# Generated by Django 3.1 on 2021-12-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0031_remove_character_portrait_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='desc_body',
            field=models.TextField(default='', max_length=384),
        ),
        migrations.AddField(
            model_name='character',
            name='desc_head',
            field=models.CharField(default='', max_length=128),
        ),
    ]
