# Generated by Django 3.1 on 2021-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0032_auto_20211203_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='school',
            field=models.CharField(choices=[('Abydos High School', 'Abydos'), ('Gehenna Academy', 'Gehenna'), ('Millennium Science School', 'Millennium'), ('Trinity General School', 'Trinity'), ('Allied Hyakkiyako Academy', 'Hyakkiyako'), ('Shanhaijing Senior Secondary School', 'Shanhaijing')], default='Abydos High School', max_length=64),
        ),
    ]
