# Generated by Django 3.1 on 2021-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0033_auto_20211205_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='school',
            field=models.CharField(choices=[('Abydos High School', 'Abydos High School'), ('Gehenna Academy', 'Gehenna Academy'), ('Millennium Science School', 'Millennium Science School'), ('Trinity General School', 'Trinity General School'), ('Allied Hyakkiyako Academy', 'Allied Hyakkiyako Academy'), ('Shanhaijing Senior Secondary School', 'Shanhaijing Senior Secondary School')], default='Abydos High School', max_length=64),
        ),
    ]
