# Generated by Django 3.1 on 2021-12-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0034_auto_20211205_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(default=15, max_length=3),
        ),
        migrations.AddField(
            model_name='character',
            name='bday',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='character',
            name='hobbies',
            field=models.CharField(default='', max_length=128),
        ),
    ]
