# Generated by Django 3.1 on 2021-12-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0035_auto_20211206_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(default=15),
        ),
    ]
