# Generated by Django 3.1 on 2021-12-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0036_auto_20211206_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.RemoveField(
            model_name='character',
            name='bday',
        ),
        migrations.RemoveField(
            model_name='character',
            name='height',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hobbies',
        ),
    ]
