# Generated by Django 3.1 on 2021-12-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0038_auto_20211206_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.CharField(choices=[('HG', 'Handgun'), ('AR', 'Assault Rifle'), ('MG', 'Machine Gun'), ('SG', 'Shotgun'), ('DSG', 'Dual Shotgun'), ('SMG', 'Submachine Gun'), ('SR', 'Sniper Rifle'), ('MT', 'Mortar'), ('GL', 'Grenade Launcher')], default='HG', max_length=3),
        ),
    ]
